version: 2
workflows:
  version: 2
  test:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: sown/builder
    steps:
      - checkout
      - run:
          name: Build SOWN Firmware
          command: make
      - store_artifacts:
          path: build/sources/imagebuilder/bin
          destination: bin
